############# Chinese navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "关于我"
url = "/about"
weight = 2

[[main]]
name = "组件展示"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "页面"

[[main]]
parent = "页面"
name = "博客文章"
url = "/blog"

[[main]]
parent = "页面"
name = "联系方式"
url = "/contact"

[[main]]
parent = "页面"
name = "作者列表"
url = "/authors"

[[main]]
parent = "页面"
name = "分类"
url = "/categories"

[[main]]
parent = "页面"
name = "404 页面"
url = "/404"


# footer menu
[[footer]]
name = "关于我"
url = "/about"
weight = 1

[[footer]]
name = "组件展示"
url = "/elements"
weight = 2

[[footer]]
name = "隐私协议"
url = "/privacy-policy"
weight = 3
