# footer copyright
copyright = "@2026 by houxuefeng"

# theme option
variables = "variables.scss"

# contact form action
contact_form_action = "#"

# newsletter form action
newsletter_form_action = "#"

# google tag manager id
tag_manager_id = ""

# footer logo
footer_logo = "images/logo.png"

# summary
summary_length = 200

# preloader
preloader = true
